### ISSUE TITLE
Feature request: Multi-monitor support

### ISSUE THREAD

**Issue by m-thorsen** [germanfr/cinnamon-transparent-panels#12]
It would be a nice addition if dynamic transparency only triggered for maximized windows on the same display as the panel.

Right now, maximized windows on monitor 2 removes the transparency from monitor 1.

**Comment by germanfr** [comment]
Thanks @m-thorsen. This is a  known issue but as I don't have two monitors right now there is nothing I can do. I'll fix it asap when I get one soon.

**Comment by k-chapin** [comment]
Great extension! I realize this issue is closed but I encountered this same behavior today. I'm curious if you've had an opportunity to tinker with multi-monitor support? If you're still developing this extension and without another display, I would be willing to help you set up a virtual machine with multiple displays to continue development.

**Comment by m-thorsen** [comment]
@k-chapin 

Seems to work fine for me (Version 4.0~20181106, Mint 20.3).   
I can have maximized windows on both or either of monitors 2 and 3 without the panel on monitor 1 turning opaque.

Could the issue be application-specific (or distro) in your case?
