### ISSUE TITLE
Feature Request: Panel Mode where...

### ISSUE THREAD

**Issue by feren** [germanfr/cinnamon-transparent-panels#13]
...if the Panel is on a Bright background, then add shade to the panel background, and if the Panel is on a Dark background, then make the panel background invisible.
aka: Like it is in Pantheon

...and a bonus would be theming possibilities for this, like how there's already theming when set to Defined By Theme.

**Comment by germanfr** [comment]
For the first one: I don't know how to do that.
I'd need to listen to background changes (which I don't know if it's even possible on Cinnamon), and then I'd need a library to take samples from the image or color or whatever it is. I've been searching for one for other things but I didn't find anything (if you know one please tell me).

For the second: that's a good idea and could be easily implemented, as long as themes' CSS overrides extension provided CSS (which I think it does), so that I can provide some defaults in case they're not themed (that was the original idea).
