### ISSUE TITLE
1 pixel transparent line at panel bottom/top

### ISSUE THREAD

**Issue by MegaV0lt** [germanfr/cinnamon-transparent-panels#29]
```
 * Cinnamon 4.08
 * Mint 19.1
 * Graphics hardware *and* driver used
   Device-2: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 390.87
 * 64 bit
 ```

**Issue**
a small line of 1px shows at bottom of the panel and at top of top panel
Theme :
![auswahl_20190103_12 51 03](https://user-images.githubusercontent.com/2804301/50636421-49b95e80-0f56-11e9-9276-f707005c42c6.jpg)

**Other information**
Tried to make a screenshot, but is very hard to see.
![auswahl_20190103_12 44 24](https://user-images.githubusercontent.com/2804301/50636445-5e95f200-0f56-11e9-89fe-7b703f2dd61c.jpg)

First posted here: https://github.com/linuxmint/Cinnamon/issues/8253

**Comment by germanfr** [comment]
Fixed, thanks.

**Comment by MegaV0lt** [comment]
I still can see the transparent line with Mint-Y-Dark Theme. Other Themes are OK and Mint-Y-Dark is ok when i use themes transparency (none). Could you please confirm that is working with the shiped themes?

**Comment by germanfr** [comment]
Yes this is working for all configurations now with Mint-Y. The issue was with semi-transparent. I have still not pushed the update to the spices, but you can test it cloning this repository or downloading [this zip](https://github.com/germanfr/cinnamon-transparent-panels/archive/master.zip) and manually placing the `transparent-panels@germanfr` folder inside `~/.local/share/cinnamon/extensions/`. It will be overwritten when you update again so no worries.
