### ISSUE TITLE
Feature Request: Blur Panel Background option?

### ISSUE THREAD

**Issue by feren** [germanfr/cinnamon-transparent-panels#7]
I'm not sure if this'd be possible, but it's something I've always wanted from day 1 on Cinnamon, even if it's only a performance reducing option for this extension...

**Comment by germanfr** [comment]
I always liked blurry backgrounds, but that is not the purpose of this extension. I'm not going to add an option for that, even if it is possible. I don't like Frankenstein apps.

**Comment by feren** [comment]
@germanfr Would there ever be the possibility in the form of another extension? It's be seriously awesome if you could do that in another extension...

**Comment by germanfr** [comment]
I have no motivation nor time to do it right now. Also, I think a better approach would be to implement it as CSS properties in the Cinnamon side. Because I bet you are thinking on Aero, and the most I could do is adding the blur to the panel, but not to the menus and other widgets. Too much effort for such a thing, it isn't worth it for me.

**Comment by feren** [comment]
@germanfr All I'd want was just panel blur if anything...

**Comment by feren** [comment]
@germanfr Also, if you ever decided you wanted to try adding blur, you may want to look into 'Show Desktop ++''s code for the blur effect

**Comment by cinnamoner** [comment]
@feren @germanfr I've been using Neon lately. So I'm somewhat out of touch with Cinnamon.
My question is: Can this thing mimic Vista title bars or not? If unfamiliar with Vista, it goes like this:
- when a window isn't maximized, the title bar is transparent (somewhat frosty though)
- when a window is maximized, it turns solid black (opaque).
Your answers are much appreciated in advance. Just wanna understand the thing once n for all.

**Comment by cinnamoner** [comment]
No answer is answer still.

**Comment by germanfr** [comment]
Sorry I receive email notifications with some delay. 

Yes, it definitely is. The themer should use the `panel-transparent` class and add a bit of opacity into it (or whatever). Then the user can select the _"defined by theme"_ option and those styles will be applied and it will be semi-transparent instead of transparent.

**Comment by cinnamoner** [comment]
@germanfr Thank you.

**Comment by germanfr** [comment]
@cinnamoner I forgot to mention that only applies to by-default opaque themes. If your theme is semi-transparent byt default and you want to turn it opaque when maximized, then it's even easier.
The themer does not have to do anything. The user has to select the _"defined by theme"_ option as well and check the option _"remove theme transparency"_. But note that this is still an experimental feature.

**Comment by cinnamoner** [comment]
@germanfr Okay, I've got it. Thanks again.
